// src/content/projects.ts
import type { Project } from '@/types';

export const projects: Project[] = [
  {
    slug: 'website-pemerintahan-subang',
    icon: 'devicon-laravel-plain colored',
    titleKey: 'project1.title',
    descKey: 'project1.desc',
    longDescKey: 'project1.longDesc',
    tags: ['Laravel 11', 'Tailwind CSS', 'Generative AI', 'Full-Stack'],
    categoryKey: 'projects.category.fullstack',
    techStack: ['Laravel 11', 'Tailwind CSS', 'PHP', 'MySQL', 'Generative AI', 'REST API'],
    year: '2025',
    featured: true,
    githubUrl: 'https://github.com/rianpramudya/WebsiteKabupatenSubang',
    image: '/Subang.jpeg',
    images: [
      '/Subang.jpeg',
      '/Subang-2.png',
      '/Subang-3.png',
      '/Subang-4.png',
      '/Subang-5.png',
      '/Subang-6.png',
    ],
    highlightKeys: [
      'project1.highlight1',
      'project1.highlight2',
      'project1.highlight3',
      'project1.highlight4',
      'project1.highlight5',
    ],
  },
  {
    slug: 'astra-logistic-tracking',
    icon: 'devicon-svelte-plain colored',
    titleKey: 'project2.title',
    descKey: 'project2.desc',
    longDescKey: 'project2.longDesc',
    tags: ['FastAPI', 'Three.js', 'SvelteKit', 'PostgreSQL', 'REST API'],
    categoryKey: 'projects.category.fullstack',
    techStack: ['FastAPI', 'SQLAlchemy', 'PostgreSQL', 'Three.js', 'SvelteKit', 'Python'],
    year: '2025',
    featured: true,
    githubUrl: 'https://github.com/rianpramudya/Astra-Project',
    image: '/Astra.jpeg',
    images: [
      '/Astra.jpeg',
      '/Astra-2.png',
      '/Astra-3.png',
      '/Astra-4.png',
      '/Astra-5.png',
      '/Astra-6.png',
      '/Astra-7.png',
      '/Astra-8.png',
      '/Astra-9.png',
      '/Astra-10.png',
      '/Astra-11.png',
      '/Astra-12.png',
      '/Astra-13.png',
      '/Astra-14.png',
      '/Astra-15.png',
      '/Astra-16.png',
      '/Astra-17.png',
      '/Astra-18.png',
    ],
    highlightKeys: [
      'project2.highlight1',
      'project2.highlight2',
      'project2.highlight3',
      'project2.highlight4',
      'project2.highlight5',
    ],
  },
  {
    slug: 'dompet-rantau',
    icon: 'devicon-php-plain colored',
    titleKey: 'project3.title',
    descKey: 'project3.desc',
    longDescKey: 'project3.longDesc',
    tags: ['Laravel 11', 'Full-Stack', 'PDF Export', 'Financial System'],
    categoryKey: 'projects.category.fullstack',
    techStack: ['Laravel 11', 'PHP', 'MySQL', 'Blade', 'Tailwind CSS'],
    year: '2025',
    featured: true,
    githubUrl: 'https://github.com/rianpramudya/Website-Manajemen-Keuangan',
    image: '/DompetRantau.png',
    images: [
      '/DompetRantau.png',
      '/DompetRantau-2.png',
      '/DompetRantau-3.png',
      '/DompetRantau-4.png',
      '/DompetRantau-5.png',
      '/DompetRantau-6.png',
    ],
    highlightKeys: [
      'project3.highlight1',
      'project3.highlight2',
      'project3.highlight3',
      'project3.highlight4',
      'project3.highlight5',
    ],
  },
  {
    slug: 'portfolio-cms',
    icon: 'devicon-tailwindcss-plain colored',
    titleKey: 'project4.title',
    descKey: 'project4.desc',
    longDescKey: 'project4.longDesc',
    tags: ['Laravel 11', 'Tailwind CSS', 'CMS', 'PDF Generator'],
    categoryKey: 'projects.category.fullstack',
    techStack: ['Laravel 11', 'Tailwind CSS', 'PHP', 'MySQL', 'PDF Generation'],
    year: '2025',
    featured: false,
    githubUrl: 'https://github.com/rianpramudya/My-Portofolio-Website-Profile-',
    image: '/Portofolio.jpeg',
    images: [
      '/Portofolio.jpeg',
      '/Portofolio-2.png',
      '/Portofolio-3.png',
      '/Portofolio-4.png',
      '/Portofolio-5.png',
      '/Portofolio-6.png',
      '/Portofolio-7.png',
      '/Portofolio-8.png',
      '/Portofolio-9.png',
      '/Portofolio-10.png',
      '/Portofolio-11.png',
    ],
    highlightKeys: [
      'project4.highlight1',
      'project4.highlight2',
      'project4.highlight3',
      'project4.highlight4',
      'project4.highlight5',
    ],
  },
  {
    slug: 'amazon-recommendation',
    icon: 'devicon-python-plain colored',
    titleKey: 'project5.title',
    descKey: 'project5.desc',
    longDescKey: 'project5.longDesc',
    tags: ['Machine Learning', 'K-Means', 'SVD', 'Streamlit', 'Data Science'],
    categoryKey: 'projects.category.ml',
    techStack: ['Python', 'Scikit-learn', 'Pandas', 'Streamlit', 'Plotly', 'Truncated SVD'],
    year: '2024',
    featured: true,
    githubUrl: 'https://github.com/rianpramudya/SistemRekomendasiAmazon',
    image: '/RecSys.jpeg',
    images: [
      '/RecSys.jpeg',
      '/RecSys-2.png',
      '/RecSys-3.png',
      '/RecSys-4.png',
      '/RecSys-5.png',
      '/RecSys-6.png',
    ],
    highlightKeys: [
      'project5.highlight1',
      'project5.highlight2',
      'project5.highlight3',
      'project5.highlight4',
      'project5.highlight5',
    ],
  },
  {
    slug: 'acnescan-yolo',
    icon: 'devicon-pytorch-plain colored',
    titleKey: 'project6.title',
    descKey: 'project6.desc',
    longDescKey: 'project6.longDesc',
    tags: ['YOLOv11', 'Computer Vision', 'SAHI', 'Streamlit', 'Deep Learning'],
    categoryKey: 'projects.category.cv',
    techStack: ['Python', 'YOLOv11', 'SAHI', 'Streamlit', 'SQLite', 'OpenCV'],
    year: '2024',
    featured: true,
    githubUrl: 'https://github.com/rianpramudya/AcneScan',
    image: '/AcneScan.jpeg',
    images: [
      '/AcneScan.jpeg',
      '/AcneScan-2.png',
      '/AcneScan-3.png',
      '/AcneScan-4.png',
      '/AcneScan-5.png',
      '/AcneScan-6.png',
    ],
    highlightKeys: [
      'project6.highlight1',
      'project6.highlight2',
      'project6.highlight3',
      'project6.highlight4',
      'project6.highlight5',
    ],
  },
];

export function getFeaturedProjects(): Project[] {
  return projects.filter(p => p.featured);
}

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find(p => p.slug === slug);
}